apiVersion: apps/v1
kind: Deployment
metadata:
  name: skin-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skin-api
  template:
    metadata:
      labels:
        app: skin-api
    spec:
      containers:
      - name: skin-api
        image: skin-api:latest        # Image locale
        imagePullPolicy: IfNotPresent # <-- IMPORTANT
        ports:
        - containerPort: 8000